//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class OnlineTestDBEntities : DbContext
    {
        public OnlineTestDBEntities()
            : base("name=OnlineTestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAnswer> tblAnswers { get; set; }
        public DbSet<tblGroupMember> tblGroupMembers { get; set; }
        public DbSet<tblGroup> tblGroups { get; set; }
        public DbSet<tblQuestionAnswer> tblQuestionAnswers { get; set; }
        public DbSet<tblQuestion> tblQuestions { get; set; }
        public DbSet<tblQuestionSubject> tblQuestionSubjects { get; set; }
        public DbSet<tblSubject> tblSubjects { get; set; }
        public DbSet<tblTestQuestion> tblTestQuestions { get; set; }
        public DbSet<tblTest> tblTests { get; set; }
        public DbSet<tblTestUserQuestion> tblTestUserQuestions { get; set; }
        public DbSet<tblTestUser> tblTestUsers { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblUserType> tblUserTypes { get; set; }
        public DbSet<tblMenu> tblMenus { get; set; }
    
        public virtual ObjectResult<usp_GetDropdownList_Result> usp_GetDropdownList(string tableName, string colID, string colText, string optional)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            var colIDParameter = colID != null ?
                new ObjectParameter("colID", colID) :
                new ObjectParameter("colID", typeof(string));
    
            var colTextParameter = colText != null ?
                new ObjectParameter("colText", colText) :
                new ObjectParameter("colText", typeof(string));
    
            var optionalParameter = optional != null ?
                new ObjectParameter("optional", optional) :
                new ObjectParameter("optional", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDropdownList_Result>("usp_GetDropdownList", tableNameParameter, colIDParameter, colTextParameter, optionalParameter);
        }
    }
}
