//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestion
    {
        public tblQuestion()
        {
            this.tblQuestionAnswers = new HashSet<tblQuestionAnswer>();
            this.tblQuestionSubjects = new HashSet<tblQuestionSubject>();
            this.tblTestQuestions = new HashSet<tblTestQuestion>();
            this.tblTestUserQuestions = new HashSet<tblTestUserQuestion>();
        }
    
        public long QID { get; set; }
        public string Question { get; set; }
        public string QuestionDesc { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> QuestionLevelID { get; set; }
        public Nullable<bool> IsStudyType { get; set; }
        public Nullable<bool> IsMultipleAns { get; set; }
    
        public virtual ICollection<tblQuestionAnswer> tblQuestionAnswers { get; set; }
        public virtual ICollection<tblQuestionSubject> tblQuestionSubjects { get; set; }
        public virtual ICollection<tblTestQuestion> tblTestQuestions { get; set; }
        public virtual ICollection<tblTestUserQuestion> tblTestUserQuestions { get; set; }
    }
}
