//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestUserQuestion
    {
        public long TestUQID { get; set; }
        public Nullable<long> TestUserID { get; set; }
        public Nullable<long> QuestionID { get; set; }
        public Nullable<long> SelectedAnswerID { get; set; }
        public Nullable<System.TimeSpan> TimeTakenToMarkAnswer { get; set; }
    
        public virtual tblAnswer tblAnswer { get; set; }
        public virtual tblQuestion tblQuestion { get; set; }
        public virtual tblTestUser tblTestUser { get; set; }
    }
}
