//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblGroupMembers = new HashSet<tblGroupMember>();
            this.tblGroupMembers1 = new HashSet<tblGroupMember>();
            this.tblGroupMembers2 = new HashSet<tblGroupMember>();
            this.tblGroups = new HashSet<tblGroup>();
            this.tblGroups1 = new HashSet<tblGroup>();
            this.tblTests = new HashSet<tblTest>();
            this.tblTests1 = new HashSet<tblTest>();
            this.tblTestUsers = new HashSet<tblTestUser>();
            this.tblUsers1 = new HashSet<tblUser>();
            this.tblUsers11 = new HashSet<tblUser>();
        }
    
        public int UID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual ICollection<tblGroupMember> tblGroupMembers { get; set; }
        public virtual ICollection<tblGroupMember> tblGroupMembers1 { get; set; }
        public virtual ICollection<tblGroupMember> tblGroupMembers2 { get; set; }
        public virtual ICollection<tblGroup> tblGroups { get; set; }
        public virtual ICollection<tblGroup> tblGroups1 { get; set; }
        public virtual ICollection<tblTest> tblTests { get; set; }
        public virtual ICollection<tblTest> tblTests1 { get; set; }
        public virtual ICollection<tblTestUser> tblTestUsers { get; set; }
        public virtual ICollection<tblUser> tblUsers1 { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual ICollection<tblUser> tblUsers11 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
    }
}
